
services:
  recetasdb:
    image: postgres:15
    container_name: recetas_postgres
    restart: always
    environment:
      POSTGRES_DB: recetasdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - recetas_net

  usuariosdb:
    image: postgres:15
    container_name: usuarios_postgres
    restart: always
    environment:
      POSTGRES_DB: usuariosdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata_usuarios:/var/lib/postgresql/data
    networks:
      - recetas_net

  recetasapi:
    build:
      context: ./RecetasService
    container_name: recetasapi
    depends_on:
      - recetasdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=recetasdb;Port=5432;Database=recetasdb;Username=postgres;Password=postgres
    ports:
      - "8002:8080"
    networks:
      - recetas_net

  analisisservice:
    build:
      context: ./AnalisisService
    container_name: analisisservice
    depends_on:
      - recetasapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8003:8080"
    networks:
      - recetas_net

  usuariosservice:
    build:
      context: ./UsuariosService
    container_name: usuariosservice
    depends_on:
      - usuariosdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=usuariosdb;Port=5432;Database=usuariosdb;Username=postgres;Password=postgres
    ports:
      - "8004:8080"
    networks:
      - recetas_net

  apigateway:
    build:
      context: ./ApiGateway
    container_name: apigateway
    depends_on:
      - recetasapi
      - analisisservice
      - usuariosservice
    ports:
      - "8001:8080"
    networks:
      - recetas_net

volumes:
  pgdata:
  pgdata_usuarios:

networks:
  recetas_net:
